# Generated by Django 5.2.15 on 2026-06-27 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('owner', models.CharField(blank=True, max_length=120, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='meetings.meeting')),
            ],
            options={
                'ordering': ['completed', 'due_date', 'created_at'],
                'indexes': [models.Index(fields=['completed'], name='actions_act_complet_cccd03_idx'), models.Index(fields=['due_date'], name='actions_act_due_dat_fd2771_idx')],
            },
        ),
    ]
