# Generated by Django 5.2.15 on 2026-06-27 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('meeting_date', models.DateTimeField(db_index=True)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-meeting_date'],
                'indexes': [models.Index(fields=['title'], name='meetings_me_title_467a82_idx'), models.Index(fields=['meeting_date'], name='meetings_me_meeting_5fb78c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.meeting')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['meeting'], name='meetings_pa_meeting_6a1478_idx')],
            },
        ),
    ]
