# Generated by Django 5.2.15 on 2026-06-27 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_name', models.CharField(max_length=120)),
                ('start_time_seconds', models.PositiveIntegerField()),
                ('end_time_seconds', models.PositiveIntegerField()),
                ('transcript_text', models.TextField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_segments', to='meetings.meeting')),
            ],
            options={
                'ordering': ['start_time_seconds'],
                'indexes': [models.Index(fields=['meeting'], name='transcripts_meeting_7af52d_idx'), models.Index(fields=['speaker_name'], name='transcripts_speaker_1dc6ae_idx'), models.Index(fields=['start_time_seconds'], name='transcripts_start_t_8d649a_idx')],
            },
        ),
    ]
